services:
  redis:
    image: redis/redis-stack:7.4.0-v1
    container_name: redis
    ports:
      - "6379:6379"
  ollama:
    image: "ollama/ollama:0.5.13"
    container_name: ollama
    profiles:
      - ollama
    ports:
      - 11434
    volumes:
      - ~/.ollama/models:/root/.ollama/models
  ollama-runner:
    container_name: ollama-runner
    profiles:
      - ollama
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    command: docker exec ollama ollama run llama3.2
    depends_on:
      - ollama