spring:
  ai:
    # Define AI provider(s) for type of models for autoconfiguration
    model:
      chat: openai
      embedding: openai
      image: openai
    # AI provider configuration
    openai:
      chat:
        options:
          model: gpt-4o
          temperature: 1.0
      image.options:
        model: dall-e-3
        size: 1024x1024
        style: natural
        response-format: b64_json
      api-key: ${SPRING_AI_OPENAI_API_KEY}